# Docs: https://www.netlifycms.org/docs/add-to-your-site/

backend:
  repo: mlibrary/design-system.lib.umich.edu
  branch: main
  name: git-gateway
  api_root: https://api.github.com
  cms_label_prefix: web-document-editor/

publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'document'
    label: 'Document'
    folder: 'pages'
    create: true
    slug: '{{slug}}'
    summary: '{{ title }} \ {{commit_author}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Parent',
          name: 'parent',
          widget: 'relation',
          collection: 'document',
          value_field: 'title',
          search_fields: ['title'],
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
