backend:
  name: github
  repo: mlibrary/design-system.lib.umich.edu
  branch: main

publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'pages'
    label: 'Page'
    folder: 'pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - label: 'Navigation' # https://www.11ty.dev/docs/plugins/navigation/
        name: 'eleventyNavigation'
        widget: 'object'
        fields:
          - { label: 'Key', name: 'key', widget: 'string' }
          - { label: 'Order', name: 'order', widget: 'number', default: 0 }
      - { label: 'Body', name: 'body', widget: 'markdown' }
