backend:
  name: github
  repo: mlibrary/design-system.lib.umich.edu
  branch: main

publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'pages'
    label: 'Document'
    folder: 'pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Abstract', name: 'abstract', widget: 'text' }
      - {
          label: 'Parent Title',
          name: 'parent',
          widget: 'select',
          options:
            [
              'None',
              'Foundations',
              'Visual elements',
              'Content',
              'Reusable designs',
              'Patterns',
              'About',
            ],
          default: 'None',
        }
      - { label: 'Content', name: 'body', widget: 'markdown' }
