# Docs: https://www.netlifycms.org/docs/add-to-your-site/

backend:
  repo: mlibrary/design-system.lib.umich.edu
  branch: main
  name: git-gateway
  api_root: https://api.github.com
  cms_label_prefix: web-document-editor/

publish_mode: editorial_workflow

media_folder: 'static/img' # Media files will be stored in the repo under images/uploads

collections:
  - name: 'pages'
    label: 'Document'
    folder: 'pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Parent Title',
          name: 'parent',
          widget: 'select',
          options:
            [
              'None',
              'Foundations',
              'Visual elements',
              'Content',
              'Reusable designs',
              'Patterns',
              'About',
            ],
          default: 'None',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
